# This resource deploys one container multiple times (adjust the replicas value to see it happening!).
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-webapp
  labels:
    app.kubernetes.io/name: dotnet-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: dotnet-webapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dotnet-webapp
    spec:
      containers:
      - name: dotnet-webapp
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        env:
        - name: EXAMPLE_VAR
          value: "Some changed value inserted by an environment value"
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          limits:
            memory: 256Mi
            cpu: 500m
          requests:
            memory: 32Mi
            cpu: 5m
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
